### ISSUE TITLE
Incompatibility with Full Tablist mod (Fabric 1.20.1)

### ISSUE THREAD

**Issue by aladairmaxwell** [Dalynkaa/Game-Highlighter#10]
Hi! Been seen that Game Highlighter is incompatible with Full Tablist mod - https://modrinth.com/mod/full-tablist

If you install both mods, Full Tablist becomes "inactive" and shows default player list with 80 players. Is there any way to fix this?

![2024-02-10_12 10 38](https://github.com/Dalynkaa/Game-Highlighter/assets/69295711/fdc4251e-1214-4aa6-a1da-20ff988c6ab2)
![2024-02-10_12 21 25](https://github.com/Dalynkaa/Game-Highlighter/assets/69295711/b7428394-c98e-4374-a62c-1ac8bc32eba5)

**Comment by Dalynkaa** [comment]
https://github.com/Dalynkaa/Game-Highlighter/releases/tag/untagged-ca51e9c1323fa46b4a62
I added my "Full Tablist mod" implementation, you can enable it in the config.

**Comment by aladairmaxwell** [comment]
404 error from the link you sent

**Comment by Dalynkaa** [comment]
https://github.com/Dalynkaa/Game-Highlighter/releases/tag/alpha-1.5
it should work.

**Comment by aladairmaxwell** [comment]
Yes, it works perfectly. Too bad I can't configure symbol and color of the highlight though

**Comment by Dalynkaa** [comment]
you can, go to the Social Menu( p - key ), and there you can set each person's Prefix and Color.

**Comment by Dalynkaa** [comment]
this is a new little update

**Comment by aladairmaxwell** [comment]
This one looks great. Thanks!

**Comment by aladairmaxwell** [comment]
Would be nice to set a default preference for this though
