### ISSUE TITLE
Mod doesn't work with Cloth Config v. 11.1.118 - 1.20.1

### ISSUE THREAD

**Issue by aladairmaxwell** [Dalynkaa/Game-Highlighter#11]
The game refuses to launch. It asks version 11.1.106 or lower.

**Comment by aladairmaxwell** [comment]
Why "wontfix" tag? Is this will not be anyhow solved?

**Comment by Dalynkaa** [comment]
I'm sorry, I accidentally clicked

**Comment by Dalynkaa** [comment]
fixed in alpha 1.6
https://github.com/Dalynkaa/Game-Highlighter/releases/tag/alpha-1.6
