### ISSUE TITLE
1.4-alpha crashes on Minecraft 1.20.1 due to 1.20.2 owo lib

### ISSUE THREAD

**Issue by Poopooracoocoo** [Dalynkaa/Game-Highlighter#9]
[crash-2024-01-04_19.00.21-client.txt](https://github.com/Dalynkaa/Game-Highlighter/files/13827552/crash-2024-01-04_19.00.21-client.txt)

[latest.log](https://github.com/Dalynkaa/Game-Highlighter/files/13827606/latest.log)

Steps to repro:
Launch instance
Click singleplayer button

**Comment by Dalynkaa** [comment]
try to use `owo-lib-0.11.1+1.20`
